### PR TITLE
ActionItemBadgeListener & MenuItem Returned

### PR DESCRIPTION
**Pull request by brianjd**

### CODE REVIEW

**Comment by mikepenz** [comment]
@brianjd thank you very much. Can you please describe the changes you did?

**Comment by brianjd** [comment]
@mikepenz Sure.  
1) I wanted to update ActionItemBadgeAdder to accept a reference to an `ActionItemBadgeListener` for it to use when calling `ActionItemBadge.update`.   
2) Changed `ActionItemBadgeListener` to return the created `MenuItem` rather than the `Menu` reference that you just provided it.

**Comment by brianjd** [comment]
@mikepenz Is there an issue?

**Comment by mikepenz** [comment]
@brianjd no no. not at all. sorry, was very busy the last few days

**Comment by brianjd** [comment]
Awesome 👍

**Pull request merged**
